#!/usr/bin/env bash
#
# Run all dotfiles installers.

# Exits the script immediately if a command exits with a non-zero status (indicating an error).
set -e

# write output to console and file
# LOG_FILE=/tmp/output-dotfiles-install.log
# exec > >(tee ${LOG_FILE}) 2>&1

# Set env DOTFILES_ROOT to current dir
export DOTFILES_ROOT=$(pwd -P)
export SCRIPT_PATH="$DOTFILES_ROOT/script"

source "$SCRIPT_PATH/helpers/utils"
source "$SCRIPT_PATH/setup_git"
source "$SCRIPT_PATH/link_dotfiles"
