#!/usr/bin/env bash
#
# Link .dotfiles
#
# Exits the script immediately if a command exits with a non-zero status (indicating an error).
set -e

info "============================================="
info "              Link .dotfiles"
info "============================================="

# link_dotfile name source dest

link_dotfile "NEOVIM" "config/nvim" ".config/nvim"
link_dotfile "Ghostty" "config/ghostty/config" ".config/ghostty/config"
link_dotfile "LazyGit" "config/lazygit/config.yml" ".config/lazygit/config.yml"
link_dotfile "Claude" "config/claude" ".claude"
link_dotfile "ZSH" "config/zsh/zshrc" ".zshrc"
link_dotfile "zprofile" "config/zsh/zprofile" ".zprofile"
link_dotfile "Mise" "config/mise/config.toml" ".config/mise/config.toml"
link_dotfile "Tmux" "config/tmux/tmux.conf" ".tmux.conf"
link_dotfile "Vim" "config/vim/vimrc" ".vimrc"
link_dotfile "gh - Github Cli" "config/gh/config.yml" ".config/gh/config.yml"
link_dotfile "Tig" "config/tig/tigrc" ".tigrc"
link_dotfile "Karabiner Elements" "config/karabiner/karabiner.json" ".config/karabiner/karabiner.json"
