#!/usr/bin/env bash
#
# Link .dotfiles
#
# Exits the script immediately if a command exits with a non-zero status (indicating an error).
set -e

info "============================================="
info "              Link .dotfiles"
info "============================================="

# link_dotfile name source dest

link_dotfile "NEOVIM" "config/nvim" ".config/nvim"
link_dotfile "Ghostty" "config/ghostty/config" ".config/ghostty/config"
link_dotfile "LazyGit" "config/lazygit/config.yml" ".config/lazygit/config.yml"
link_dotfile "Claude" "config/claude" ".claude"
