#!/usr/bin/env bash
#
# Configuring MacOS defaults
#
# Exits the script immediately if a command exits with a non-zero status (indicating an error).
set -e

info "============================================="
info "           Configuring MacOS"
info "============================================="


# create screenshot folder
mkdir -p ~/Desktop/screenshots

# Save screenshots ~/Desktop/screenshots
defaults write com.apple.screencapture location -string "${HOME}/Desktop/screenshots"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

# Finder: show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# Finder PathBar
defaults write com.apple.finder ShowPathbar -bool true

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# Expand the following File Info panes:
# “General”, “Open with”, and “Sharing & Permissions”
defaults write com.apple.finder FXInfoPanesExpanded -dict \
  General -bool true \
  OpenWith -bool true \
  Privileges -bool true

# Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Hot corners
defaults write com.apple.dock wvous-br-corner -int 13
defaults write com.apple.dock wvous-br-modifier -int 1048576

# Batery Percentage
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# KeyRepeat ( Keyboard speed )
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 48

# Don’t show recent applications in Dock
defaults write com.apple.dock show-recents -bool false

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

###############################################################################
# Transmission.app                                                            #
###############################################################################

# Don’t prompt for confirmation before downloading
defaults write org.m0k.transmission DownloadAsk -bool false

# Trash original torrent files
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Hide the donate message
defaults write org.m0k.transmission WarningDonate -bool false
# Hide the legal disclaimer
defaults write org.m0k.transmission WarningLegal -bool false

# restart affected applications
for app in "cfprefsd" \
  "Dock" \
  "Finder"; do
  killall "${app}" &> /dev/null || true
done

success "macOS defaults configured!"
info "Some changes require a logout/restart to take effect."
