#!/usr/bin/env bash
#
# Install Homebrew and Packages
#
# Exits the script immediately if a command exits with a non-zero status (indicating an error).
set -e

info "============================================="
info "            Installing xcode-select"
info "============================================="

if ! command -v xcode-select >/dev/null 2>&1; then
  xcode-select --install
  success "xcode-select instalado com sucesso"
else
  success "xcode-select já instalado"
fi

